<?php
namespace AppBundle\Tests\Entity;

use AppBundle\Entity\TekniskIsoleringTiltagDetail;
use AppBundle\Entity\TekniskIsoleringTiltag;

class TekniskIsoleringTiltagDetailTest extends EntityTestCase {
  public function testCompute() {
    $detail = $this->getTekniskIsoleringTiltagDetail(array(
      'Tilvalgt' => true,
      'LåstAfEnergirådgiver' => false,
      'BeskrivelseType' => 'EKSEMPEL',
      'Type' => 'Rør',
      'DriftstidTÅr' => 8760,
      'UdvDiameterMm' => 48.3,
      'EksistIsolMm' => 0.00,
      'TankVolL' => 0,
      'TempOmgivel°C' => 18,
      'TempMedie°C' => 55,
      'RørlængdeEllerHøjdeAfVvbM' => 3,
      'NyttiggjortVarme' => 1,
      'NyIsolMm' => 50,
      'StandardinvestKrM²EllerKrM' => 500,
      'Prisfaktor' => 1,
    ));

    $this->assertProperties($detail, array(
      'rørstørrelseMmÆkvivalent' => 48.3,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.05,
      'varmeledningsevnePåNyIsoleringWMK' => 0.044,
      'arealAfBeholderM²' => 0,
      'investeringKr' => 1500,
      'eksistVarmetabKwh' => 1327.903751490595,
      'nytVarmetabKwh' => 226.3283404964517,
      'varmebespKwhÅr' => 1101.575410994144,
      // @FIXME (Division by zero)
      // 'simpelTilbagebetalingstidÅr' => 2.773291584226232,
      'nutidsværdiSetOver15ÅrKr' => 4080.981554517602,
      'kwhBesparelseElFraVærket' => 0,
      'kwhBesparelseVarmeFraVærket' => 1101.575410994144,
    ));
  }

  private function getTekniskIsoleringTiltagDetail(array $values) {
    $tiltag = new TekniskIsoleringTiltag();
    $tiltag->setLevetid(10);
    $detail = new TekniskIsoleringTiltagDetail();
    $detail->setTiltag($tiltag);
    $this->loadEntity($detail, $values);

    return $detail;
  }

  private $tests = array (
  0 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => true,
      'BeskrivelseType' => 'EKSEMPEL',
      'Type' => 'Rør',
      'DriftstidTÅr' => 8760,
      'UdvDiameterMm' => 48.299999999999997,
      'EksistIsolMm' => 0,
      'TankVolL' => NULL,
      'TempOmgivel°C' => 18,
      'TempMedie°C' => 55,
      'RørlængdeEllerHøjdeAfVvbM' => 3,
      'NyttiggjortVarme' => 1,
      'NyIsolMm' => 50,
      'StandardinvestKrM²EllerKrM' => 500,
      'Prisfaktor' => 1,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 48.299999999999997,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 1500,
      'eksistVarmetabKwh' => 1327.9037514905951,
      'nytVarmetabKwh' => 226.32834049645166,
      'varmebespKwhÅr' => 1101.5754109941436,
      'simpelTilbagebetalingstidÅr' => 2.7732915842262322,
      'nutidsværdiSetOver15ÅrKr' => 4080.9815545176025,
      'kwhBesparelseElFraVærket' => 0,
      'kwhBesparelseVarmeFraVærket' => 1101.5754109941436,
    ),
  ),
  1 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => true,
      'BeskrivelseType' => 'Manglende isoleringskappe til Alpha 2 pumpe i depot kantine lokale C-11',
      'Type' => 'Rør',
      'DriftstidTÅr' => 5448,
      'UdvDiameterMm' => 33.700000000000003,
      'EksistIsolMm' => 0,
      'TankVolL' => NULL,
      'TempOmgivel°C' => 21,
      'TempMedie°C' => 40,
      'RørlængdeEllerHøjdeAfVvbM' => 2,
      'NyttiggjortVarme' => 0.5,
      'NyIsolMm' => 50,
      'StandardinvestKrM²EllerKrM' => 110,
      'Prisfaktor' => 1,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 33.700000000000003,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 220,
      'eksistVarmetabKwh' => 98.63089700541866,
      'nytVarmetabKwh' => 19.719056859686159,
      'varmebespKwhÅr' => 78.911840145732498,
      'simpelTilbagebetalingstidÅr' => 5.6780474550918294,
      'nutidsværdiSetOver15ÅrKr' => 130.64554030993793,
      'kwhBesparelseElFraVærket' => 0,
      'kwhBesparelseVarmeFraVærket' => 78.911840145732498,
    ),
  ),
  2 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => true,
      'BeskrivelseType' => 'Manglende isoleringskappe til Alpha 2 pumpe i teknikrumsgang H-00',
      'Type' => 'Rør',
      'DriftstidTÅr' => 5448,
      'UdvDiameterMm' => 33.700000000000003,
      'EksistIsolMm' => 0,
      'TankVolL' => NULL,
      'TempOmgivel°C' => 24,
      'TempMedie°C' => 60,
      'RørlængdeEllerHøjdeAfVvbM' => 2,
      'NyttiggjortVarme' => 0.80000000000000004,
      'NyIsolMm' => 50,
      'StandardinvestKrM²EllerKrM' => 110,
      'Prisfaktor' => 1,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 33.700000000000003,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 220,
      'eksistVarmetabKwh' => 299.00735092169032,
      'nytVarmetabKwh' => 59.779877637785411,
      'varmebespKwhÅr' => 239.22747328390491,
      'simpelTilbagebetalingstidÅr' => 1.872967042478207,
      'nutidsværdiSetOver15ÅrKr' => 1038.2808552513443,
      'kwhBesparelseElFraVærket' => 0,
      'kwhBesparelseVarmeFraVærket' => 239.22747328390491,
    ),
  ),
  3 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => true,
      'BeskrivelseType' => '11 isoleringspuder i teknikrum H-03 på fremløb',
      'Type' => 'Rør',
      'DriftstidTÅr' => 5448,
      'UdvDiameterMm' => 120,
      'EksistIsolMm' => 0,
      'TankVolL' => NULL,
      'TempOmgivel°C' => 25,
      'TempMedie°C' => 70,
      'RørlængdeEllerHøjdeAfVvbM' => 3.2999999999999998,
      'NyttiggjortVarme' => 0.80000000000000004,
      'NyIsolMm' => 40,
      'StandardinvestKrM²EllerKrM' => 200,
      'Prisfaktor' => 1,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 120,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 660,
      'eksistVarmetabKwh' => 2195.973868045055,
      'nytVarmetabKwh' => 319.68298126523564,
      'varmebespKwhÅr' => 1876.2908867798194,
      'simpelTilbagebetalingstidÅr' => 0.7164110473591021,
      'nutidsværdiSetOver15ÅrKr' => 9674.3648741036413,
      'kwhBesparelseElFraVærket' => 0,
      'kwhBesparelseVarmeFraVærket' => 1876.2908867798194,
    ),
  ),
  4 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => true,
      'BeskrivelseType' => '3 isoleringspuder teknikrum H-03 returløb',
      'Type' => 'Rør',
      'DriftstidTÅr' => 5448,
      'UdvDiameterMm' => 120,
      'EksistIsolMm' => 0,
      'TankVolL' => NULL,
      'TempOmgivel°C' => 25,
      'TempMedie°C' => 40,
      'RørlængdeEllerHøjdeAfVvbM' => 1,
      'NyttiggjortVarme' => 0.80000000000000004,
      'NyIsolMm' => 40,
      'StandardinvestKrM²EllerKrM' => 200,
      'Prisfaktor' => 1,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 120,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 200,
      'eksistVarmetabKwh' => 221.81554222677323,
      'nytVarmetabKwh' => 32.291210228811686,
      'varmebespKwhÅr' => 189.52433199796155,
      'simpelTilbagebetalingstidÅr' => 2.1492331420773061,
      'nutidsværdiSetOver15ÅrKr' => 785.79898612428406,
      'kwhBesparelseElFraVærket' => 0,
      'kwhBesparelseVarmeFraVærket' => 189.52433199796155,
    ),
  ),
  5 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => true,
      'BeskrivelseType' => '4 isoleringspuder teknikrum H-03 blandesløjfe',
      'Type' => 'Rør',
      'DriftstidTÅr' => 5448,
      'UdvDiameterMm' => 120,
      'EksistIsolMm' => 0,
      'TankVolL' => NULL,
      'TempOmgivel°C' => 25,
      'TempMedie°C' => 55,
      'RørlængdeEllerHøjdeAfVvbM' => 2.2000000000000002,
      'NyttiggjortVarme' => 0.80000000000000004,
      'NyIsolMm' => 40,
      'StandardinvestKrM²EllerKrM' => 200,
      'Prisfaktor' => 1,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 120,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 440.00000000000006,
      'eksistVarmetabKwh' => 975.98838579780227,
      'nytVarmetabKwh' => 142.08132500677138,
      'varmebespKwhÅr' => 833.90706079103086,
      'simpelTilbagebetalingstidÅr' => 1.0746165710386533,
      'nutidsværdiSetOver15ÅrKr' => 4088.9721108933136,
      'kwhBesparelseElFraVærket' => 0,
      'kwhBesparelseVarmeFraVærket' => 833.90706079103086,
    ),
  ),
  6 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => true,
      'BeskrivelseType' => '1 isoleringspude teknikrumsgang H-00',
      'Type' => 'Rør',
      'DriftstidTÅr' => 5448,
      'UdvDiameterMm' => 45,
      'EksistIsolMm' => 0,
      'TankVolL' => NULL,
      'TempOmgivel°C' => 24,
      'TempMedie°C' => 40,
      'RørlængdeEllerHøjdeAfVvbM' => 0.29999999999999999,
      'NyttiggjortVarme' => 0.80000000000000004,
      'NyIsolMm' => 40,
      'StandardinvestKrM²EllerKrM' => 200,
      'Prisfaktor' => 1,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 45,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 60,
      'eksistVarmetabKwh' => 26.617865067212779,
      'nytVarmetabKwh' => 5.2584547567042428,
      'varmebespKwhÅr' => 21.359410310508537,
      'simpelTilbagebetalingstidÅr' => 5.7211126567433332,
      'nutidsværdiSetOver15ÅrKr' => 34.831497596893641,
      'kwhBesparelseElFraVærket' => 0,
      'kwhBesparelseVarmeFraVærket' => 21.359410310508537,
    ),
  ),
  7 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => true,
      'BeskrivelseType' => 'Rørisolering til 0,4 m rør placeret i depot til kantine, lokale C-11',
      'Type' => 'Rør',
      'DriftstidTÅr' => 5448,
      'UdvDiameterMm' => 22,
      'EksistIsolMm' => 0,
      'TankVolL' => NULL,
      'TempOmgivel°C' => 21,
      'TempMedie°C' => 40,
      'RørlængdeEllerHøjdeAfVvbM' => 0.40000000000000002,
      'NyttiggjortVarme' => 0.5,
      'NyIsolMm' => 40,
      'StandardinvestKrM²EllerKrM' => 90,
      'Prisfaktor' => 1,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 22,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 36,
      'eksistVarmetabKwh' => 12.877624534832114,
      'nytVarmetabKwh' => 3.5117318359837024,
      'varmebespKwhÅr' => 9.3658926988484108,
      'simpelTilbagebetalingstidÅr' => 7.8283787737424904,
      'nutidsværdiSetOver15ÅrKr' => 1.3679346604311036,
      'kwhBesparelseElFraVærket' => 0,
      'kwhBesparelseVarmeFraVærket' => 9.3658926988484108,
    ),
  ),
  8 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 0,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 0,
      'eksistVarmetabKwh' => '',
      'nytVarmetabKwh' => '',
      'varmebespKwhÅr' => '',
      'simpelTilbagebetalingstidÅr' => '',
      'nutidsværdiSetOver15ÅrKr' => '',
      'kwhBesparelseElFraVærket' => '',
      'kwhBesparelseVarmeFraVærket' => '',
    ),
  ),
  9 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 0,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 0,
      'eksistVarmetabKwh' => '',
      'nytVarmetabKwh' => '',
      'varmebespKwhÅr' => '',
      'simpelTilbagebetalingstidÅr' => '',
      'nutidsværdiSetOver15ÅrKr' => '',
      'kwhBesparelseElFraVærket' => '',
      'kwhBesparelseVarmeFraVærket' => '',
    ),
  ),
  10 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 0,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 0,
      'eksistVarmetabKwh' => '',
      'nytVarmetabKwh' => '',
      'varmebespKwhÅr' => '',
      'simpelTilbagebetalingstidÅr' => '',
      'nutidsværdiSetOver15ÅrKr' => '',
      'kwhBesparelseElFraVærket' => '',
      'kwhBesparelseVarmeFraVærket' => '',
    ),
  ),
  11 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 0,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 0,
      'eksistVarmetabKwh' => '',
      'nytVarmetabKwh' => '',
      'varmebespKwhÅr' => '',
      'simpelTilbagebetalingstidÅr' => '',
      'nutidsværdiSetOver15ÅrKr' => '',
      'kwhBesparelseElFraVærket' => '',
      'kwhBesparelseVarmeFraVærket' => '',
    ),
  ),
  12 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 0,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 0,
      'eksistVarmetabKwh' => '',
      'nytVarmetabKwh' => '',
      'varmebespKwhÅr' => '',
      'simpelTilbagebetalingstidÅr' => '',
      'nutidsværdiSetOver15ÅrKr' => '',
      'kwhBesparelseElFraVærket' => '',
      'kwhBesparelseVarmeFraVærket' => '',
    ),
  ),
  13 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => 0,
      'varmeledningsevnePåEksistIsoleringWMK' => 0.050000000000000003,
      'varmeledningsevnePåNyIsoleringWMK' => 0.043999999999999997,
      'arealAfBeholderM²' => '',
      'investeringKr' => 0,
      'eksistVarmetabKwh' => '',
      'nytVarmetabKwh' => '',
      'varmebespKwhÅr' => '',
      'simpelTilbagebetalingstidÅr' => '',
      'nutidsværdiSetOver15ÅrKr' => '',
      'kwhBesparelseElFraVærket' => '',
      'kwhBesparelseVarmeFraVærket' => '',
    ),
  ),
  14 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  15 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  16 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  17 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  18 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  19 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  20 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  21 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  22 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  23 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  24 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  25 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  26 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  27 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  28 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  29 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  30 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  31 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  32 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  33 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  34 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  35 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  36 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  37 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  38 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  39 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  40 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  41 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  42 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  43 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  44 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  45 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  46 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  47 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  48 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  49 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  50 =>
  array (
    0 =>
    array (
      'LåstAfEnergirådgiver' => false,
      'Tilvalgt' => false,
      'BeskrivelseType' => NULL,
      'Type' => NULL,
      'DriftstidTÅr' => NULL,
      'UdvDiameterMm' => NULL,
      'EksistIsolMm' => NULL,
      'TankVolL' => NULL,
      'TempOmgivel°C' => NULL,
      'TempMedie°C' => NULL,
      'RørlængdeEllerHøjdeAfVvbM' => NULL,
      'NyttiggjortVarme' => NULL,
      'NyIsolMm' => NULL,
      'StandardinvestKrM²EllerKrM' => NULL,
      'Prisfaktor' => NULL,
    ),
    1 =>
    array (
      'rørstørrelseMmÆkvivalent' => NULL,
      'varmeledningsevnePåEksistIsoleringWMK' => NULL,
      'varmeledningsevnePåNyIsoleringWMK' => NULL,
      'arealAfBeholderM²' => NULL,
      'investeringKr' => NULL,
      'eksistVarmetabKwh' => NULL,
      'nytVarmetabKwh' => NULL,
      'varmebespKwhÅr' => NULL,
      'simpelTilbagebetalingstidÅr' => NULL,
      'nutidsværdiSetOver15ÅrKr' => NULL,
      'kwhBesparelseElFraVærket' => NULL,
      'kwhBesparelseVarmeFraVærket' => NULL,
    ),
  ),
  );
}
