<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160815132736 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE Baseline CHANGE elForbrugsdataSekundaer1Forbrug elForbrugsdataSekundaer1Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE elForbrugsdataSekundaer2Forbrug elForbrugsdataSekundaer2Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE elForbrugsdataSekundaer3Forbrug elForbrugsdataSekundaer3Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE elBaselineFastsatForEjendom elBaselineFastsatForEjendom NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer1Forbrug varmeForbrugsdataPrimaer1Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer2Forbrug varmeForbrugsdataPrimaer2Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer3Forbrug varmeForbrugsdataPrimaer3Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer1SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataPrimaer1SamletVarmeforbrugJuniJuliAugust NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer2SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataPrimaer2SamletVarmeforbrugJuniJuliAugust NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer3SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataPrimaer3SamletVarmeforbrugJuniJuliAugust NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer1GDPeriode varmeForbrugsdataPrimaer1GDPeriode NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer2GDPeriode varmeForbrugsdataPrimaer2GDPeriode NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer3GDPeriode varmeForbrugsdataPrimaer3GDPeriode NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer1Forbrug varmeForbrugsdataSekundaer1Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer2Forbrug varmeForbrugsdataSekundaer2Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer3Forbrug varmeForbrugsdataSekundaer3Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer1SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataSekundaer1SamletVarmeforbrugJuniJuliAugust NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer2SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataSekundaer2SamletVarmeforbrugJuniJuliAugust NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer3SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataSekundaer3SamletVarmeforbrugJuniJuliAugust NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer1GDPeriode varmeForbrugsdataSekundaer1GDPeriode NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer2GDPeriode varmeForbrugsdataSekundaer2GDPeriode NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer3GDPeriode varmeForbrugsdataSekundaer3GDPeriode NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeGAFForbrug varmeGAFForbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeGUFForbrug varmeGUFForbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeStrafafkoelingsafgift varmeStrafafkoelingsafgift NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeStrafafkoelingsafgiftKorrektion varmeStrafafkoelingsafgiftKorrektion NUMERIC(16, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE Baseline_audit CHANGE elForbrugsdataSekundaer1Forbrug elForbrugsdataSekundaer1Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE elForbrugsdataSekundaer2Forbrug elForbrugsdataSekundaer2Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE elForbrugsdataSekundaer3Forbrug elForbrugsdataSekundaer3Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE elBaselineFastsatForEjendom elBaselineFastsatForEjendom NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer1Forbrug varmeForbrugsdataPrimaer1Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer2Forbrug varmeForbrugsdataPrimaer2Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer3Forbrug varmeForbrugsdataPrimaer3Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer1SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataPrimaer1SamletVarmeforbrugJuniJuliAugust NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer2SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataPrimaer2SamletVarmeforbrugJuniJuliAugust NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer3SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataPrimaer3SamletVarmeforbrugJuniJuliAugust NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer1GDPeriode varmeForbrugsdataPrimaer1GDPeriode NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer2GDPeriode varmeForbrugsdataPrimaer2GDPeriode NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer3GDPeriode varmeForbrugsdataPrimaer3GDPeriode NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer1Forbrug varmeForbrugsdataSekundaer1Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer2Forbrug varmeForbrugsdataSekundaer2Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer3Forbrug varmeForbrugsdataSekundaer3Forbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer1SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataSekundaer1SamletVarmeforbrugJuniJuliAugust NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer2SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataSekundaer2SamletVarmeforbrugJuniJuliAugust NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer3SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataSekundaer3SamletVarmeforbrugJuniJuliAugust NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer1GDPeriode varmeForbrugsdataSekundaer1GDPeriode NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer2GDPeriode varmeForbrugsdataSekundaer2GDPeriode NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer3GDPeriode varmeForbrugsdataSekundaer3GDPeriode NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeGAFForbrug varmeGAFForbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeGUFForbrug varmeGUFForbrug NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeStrafafkoelingsafgift varmeStrafafkoelingsafgift NUMERIC(16, 4) DEFAULT NULL, CHANGE varmeStrafafkoelingsafgiftKorrektion varmeStrafafkoelingsafgiftKorrektion NUMERIC(16, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE Rapport CHANGE BaselineEl BaselineEl NUMERIC(16, 4) DEFAULT NULL, CHANGE BaselineVarmeGUF BaselineVarmeGUF NUMERIC(16, 4) DEFAULT NULL, CHANGE BaselineVarmeGAF BaselineVarmeGAF NUMERIC(16, 4) DEFAULT NULL, CHANGE BaselineVand BaselineVand NUMERIC(16, 4) DEFAULT NULL, CHANGE BaselineStrafAfkoeling BaselineStrafAfkoeling NUMERIC(16, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE Rapport_audit CHANGE BaselineEl BaselineEl NUMERIC(16, 4) DEFAULT NULL, CHANGE BaselineVarmeGUF BaselineVarmeGUF NUMERIC(16, 4) DEFAULT NULL, CHANGE BaselineVarmeGAF BaselineVarmeGAF NUMERIC(16, 4) DEFAULT NULL, CHANGE BaselineVand BaselineVand NUMERIC(16, 4) DEFAULT NULL, CHANGE BaselineStrafAfkoeling BaselineStrafAfkoeling NUMERIC(16, 4) DEFAULT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE Baseline CHANGE elForbrugsdataSekundaer1Forbrug elForbrugsdataSekundaer1Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE elForbrugsdataSekundaer2Forbrug elForbrugsdataSekundaer2Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE elForbrugsdataSekundaer3Forbrug elForbrugsdataSekundaer3Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE elBaselineFastsatForEjendom elBaselineFastsatForEjendom NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer1Forbrug varmeForbrugsdataPrimaer1Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer2Forbrug varmeForbrugsdataPrimaer2Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer3Forbrug varmeForbrugsdataPrimaer3Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer1SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataPrimaer1SamletVarmeforbrugJuniJuliAugust NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer2SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataPrimaer2SamletVarmeforbrugJuniJuliAugust NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer3SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataPrimaer3SamletVarmeforbrugJuniJuliAugust NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer1GDPeriode varmeForbrugsdataPrimaer1GDPeriode NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer2GDPeriode varmeForbrugsdataPrimaer2GDPeriode NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer3GDPeriode varmeForbrugsdataPrimaer3GDPeriode NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer1Forbrug varmeForbrugsdataSekundaer1Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer2Forbrug varmeForbrugsdataSekundaer2Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer3Forbrug varmeForbrugsdataSekundaer3Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer1SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataSekundaer1SamletVarmeforbrugJuniJuliAugust NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer2SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataSekundaer2SamletVarmeforbrugJuniJuliAugust NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer3SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataSekundaer3SamletVarmeforbrugJuniJuliAugust NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer1GDPeriode varmeForbrugsdataSekundaer1GDPeriode NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer2GDPeriode varmeForbrugsdataSekundaer2GDPeriode NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer3GDPeriode varmeForbrugsdataSekundaer3GDPeriode NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeGAFForbrug varmeGAFForbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeGUFForbrug varmeGUFForbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeStrafafkoelingsafgift varmeStrafafkoelingsafgift NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeStrafafkoelingsafgiftKorrektion varmeStrafafkoelingsafgiftKorrektion NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE Baseline_audit CHANGE elForbrugsdataSekundaer1Forbrug elForbrugsdataSekundaer1Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE elForbrugsdataSekundaer2Forbrug elForbrugsdataSekundaer2Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE elForbrugsdataSekundaer3Forbrug elForbrugsdataSekundaer3Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE elBaselineFastsatForEjendom elBaselineFastsatForEjendom NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer1Forbrug varmeForbrugsdataPrimaer1Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer2Forbrug varmeForbrugsdataPrimaer2Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer3Forbrug varmeForbrugsdataPrimaer3Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer1SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataPrimaer1SamletVarmeforbrugJuniJuliAugust NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer2SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataPrimaer2SamletVarmeforbrugJuniJuliAugust NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer3SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataPrimaer3SamletVarmeforbrugJuniJuliAugust NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer1GDPeriode varmeForbrugsdataPrimaer1GDPeriode NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer2GDPeriode varmeForbrugsdataPrimaer2GDPeriode NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataPrimaer3GDPeriode varmeForbrugsdataPrimaer3GDPeriode NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer1Forbrug varmeForbrugsdataSekundaer1Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer2Forbrug varmeForbrugsdataSekundaer2Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer3Forbrug varmeForbrugsdataSekundaer3Forbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer1SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataSekundaer1SamletVarmeforbrugJuniJuliAugust NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer2SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataSekundaer2SamletVarmeforbrugJuniJuliAugust NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer3SamletVarmeforbrugJuniJuliAugust varmeForbrugsdataSekundaer3SamletVarmeforbrugJuniJuliAugust NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer1GDPeriode varmeForbrugsdataSekundaer1GDPeriode NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer2GDPeriode varmeForbrugsdataSekundaer2GDPeriode NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeForbrugsdataSekundaer3GDPeriode varmeForbrugsdataSekundaer3GDPeriode NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeGAFForbrug varmeGAFForbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeGUFForbrug varmeGUFForbrug NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeStrafafkoelingsafgift varmeStrafafkoelingsafgift NUMERIC(14, 4) DEFAULT NULL, CHANGE varmeStrafafkoelingsafgiftKorrektion varmeStrafafkoelingsafgiftKorrektion NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE Rapport CHANGE BaselineEl BaselineEl NUMERIC(10, 4) DEFAULT NULL, CHANGE BaselineVarmeGUF BaselineVarmeGUF NUMERIC(10, 4) DEFAULT NULL, CHANGE BaselineVarmeGAF BaselineVarmeGAF NUMERIC(10, 4) DEFAULT NULL, CHANGE BaselineVand BaselineVand NUMERIC(10, 4) DEFAULT NULL, CHANGE BaselineStrafAfkoeling BaselineStrafAfkoeling NUMERIC(10, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE Rapport_audit CHANGE BaselineEl BaselineEl NUMERIC(10, 4) DEFAULT NULL, CHANGE BaselineVarmeGUF BaselineVarmeGUF NUMERIC(10, 4) DEFAULT NULL, CHANGE BaselineVarmeGAF BaselineVarmeGAF NUMERIC(10, 4) DEFAULT NULL, CHANGE BaselineVand BaselineVand NUMERIC(10, 4) DEFAULT NULL, CHANGE BaselineStrafAfkoeling BaselineStrafAfkoeling NUMERIC(10, 4) DEFAULT NULL');
    }
}
