<?php
/**
 * @file
 * @TODO: Missing description.
 */

namespace AppBundle\Entity\BelysningTiltagDetail;

use Doctrine\ORM\EntityRepository;

/**
 * LyskildeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LyskildeRepository extends EntityRepository {
  /**
   * Check if entity can be removed (deleted). If not, return an error message.
   *
   * @return string|null
   */
  public function getRemoveErrorMessage(Lyskilde $lyskilde) {
    $query = $this->_em->createQuery('SELECT d FROM AppBundle:BelysningTiltagDetail d WHERE d.lyskilde = :lyskilde');
    $query->setParameter('lyskilde', $lyskilde);
    $result = $query->getResult();

    if ($result) {
      return 'lyskilde.error.in_use';
    }

    return null;
  }

}
