<?php
/**
 * @file
 * @TODO: Missing description.
 */

namespace AppBundle\Entity\BelysningTiltagDetail;

use Doctrine\ORM\EntityRepository;

/**
 * NytArmaturRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NytArmaturRepository extends EntityRepository {
  /**
   * Check if entity can be removed (deleted). If not, return an error message.
   *
   * @return string|null
   */
  public function getRemoveErrorMessage(NytArmatur $nytArmatur) {
    $query = $this->_em->createQuery('SELECT d FROM AppBundle:BelysningTiltagDetail d WHERE d.nytArmatur = :nytArmatur');
    $query->setParameter('nytArmatur', $nytArmatur);
    $result = $query->getResult();

    if ($result) {
      return 'nytarmatur.error.in_use';
    }

    return null;
  }

}
