<?php

namespace AppBundle\Entity\TekniskIsoleringTiltagDetail;

use Doctrine\ORM\EntityRepository;

/**
 * KomponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KomponentRepository extends EntityRepository {
  /**
   * Check if entity can be removed (deleted). If not, return an error message.
   *
   * @return string|null
   */
  public function getRemoveErrorMessage(Komponent $komponent) {
    $query = $this->_em->createQuery('SELECT d FROM AppBundle:TekniskIsoleringTiltagDetail d WHERE d.komponent = :komponent');
    $query->setParameter('komponent', $komponent);
    $result = $query->getResult();

    if ($result) {
      return 'komponent.error.in_use';
    }

    return null;
  }

}
