<?php

namespace AppBundle\Entity\RapportSektioner;

use Doctrine\ORM\EntityRepository;

/**
 * RapportSektionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportSektionRepository extends EntityRepository {

    /**
     * Create a new RapportSektion based on type
     *
     * @param string $type
     * @param array $params
     *
     * @return RapportSektion|NULL
     */
    public function create($type, array $params = array())
    {
        $params['entityManager'] = $this->_em;
        $className = RapportSektion::getRapportSektionClassByType($type);
        return class_exists($className) ? new $className($params) : NULL;
    }

}
