<?php

namespace AppBundle\Entity\RapportSektioner;

use Doctrine\ORM\EntityRepository;

/**
 * RapportSektionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportSektionRepository extends EntityRepository {

    /**
     * Create a new RapportSektion based on type
     *
     * @param string $type
     * @param array $params
     *
     * @return RapportSektion|NULL
     */
    public function create($type, array $params = array())
    {
        $entity = NULL;
        $className = RapportSektion::getRapportSektionClassByType($type);
        if (class_exists($className)) {
            /** @var RapportSektion $entity */
            $entity = new $className($params);

            $entity->init($this->getEntityManager());
        }

        return $entity;
    }

}
