<?php
/**
 * @file
 * @TODO: Missing description.
 */

namespace AppBundle\Entity;

use AppBundle\DBAL\Types\BygningStatusType;
use Doctrine\ORM\EntityRepository;

/**
 * BygningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BygningRepository extends EntityRepository {
  /**
   * Check if a User has access to a Bygning
   *
   * @param User $user
   * @param Bygning $bygning
   * @return bool
   */
  public function hasAccess(User $user, Bygning $bygning) {
    if ($this->hasFullAccess($user)) {
      return TRUE;
    }

    $bygninger = $this->findByUser($user);
    return $bygninger && in_array($bygning, $bygninger);
  }

  /**
   * Find all Bygning that a User has access to
   *
   * @param User $user
   * @param bool $returnQuery
   * @return array|\Doctrine\ORM\Query
   */
  public function findByUser(User $user, $returnQuery = FALSE, $onlyOwnBuildings = FALSE) {
    if ($this->hasFullAccess($user) && !$onlyOwnBuildings) {
      $query = $this->_em->createQuery("SELECT b FROM AppBundle:Bygning b");
    }
    else {
      $query = $this->_em->createQuery("SELECT b FROM AppBundle:Bygning b WHERE :user MEMBER OF b.users");
      $query->setParameter('user', $user);
    }

    return $returnQuery ? $query : $query->getResult();
  }

  /**
   * Find all Bygning from given segment
   *
   * @param Segment $segment
   * @param bool $returnQuery
   * @return array|\Doctrine\ORM\Query
   */
  public function findBySegment(Segment $segment, $returnQuery = FALSE) {
    $query = $this->_em->createQuery("SELECT b FROM AppBundle:Bygning b WHERE :segment = b.segment");
    $query->setParameter('segment', $segment);

    return $returnQuery ? $query : $query->getResult();
  }

  /**
   * Search all Bygning that a User has access to
   *
   * @param User $user
   * @param bool $returnQuery
   * @return array|\Doctrine\ORM\Query
   */
  public function searchByUser(User $user, $search) {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('b')
      ->from('AppBundle:Bygning', 'b');

    if (!empty($search['navn'])) {
      $qb->andWhere('b.navn LIKE :navn')
        ->setParameter('navn', '%' . $search['navn'] . '%');
    }

    if (!empty($search['adresse'])) {
      $qb->andWhere('b.adresse LIKE :adresse')
        ->setParameter('adresse', '%' . $search['adresse'] . '%');
    }

    if (!empty($search['postBy'])) {
      $qb->andWhere('b.postBy LIKE :postBy')
        ->setParameter('postBy', '%' . $search['postBy'] . '%');
    }

    if (!empty($search['bygId'])) {
      $qb->andWhere('b.bygId = :bygId')
        ->setParameter('bygId', $search['bygId']);
    }

    if (!empty($search['postnummer'])) {
      $qb->andWhere('b.postnummer = :postnummer')
        ->setParameter('postnummer', $search['postnummer']);
    }

    if (!empty($search['status'])) {
      $qb->andWhere('b.status = :status')
        ->setParameter('status', $search['status']);
    }

    if (!empty($search['segment'])) {
      $qb->andWhere('b.segment = :segment')
        ->setParameter('segment', $search['segment']);
    }

    if (!$this->hasFullAccess($user)) {
      $qb->andWhere(':user MEMBER OF b.users');
      $qb->setParameter('user', $user);
    }

    return $qb->getQuery();
  }

  /**
   * Search all Bygning that a User has access to with attached report
   *
   * @param User $user
   * @param array $search
   * @return array|\Doctrine\ORM\Query
   */
  public function searchByUserWithReport(User $user, $search) {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('b', 'r')
      ->from('AppBundle:Bygning', 'b')
      ->leftJoin('b.rapport', 'r')
      ->leftJoin('b.segment', 's');

    if (!empty($search['navn'])) {
      $qb->andWhere('b.navn LIKE :navn')
        ->setParameter('navn', '%' . $search['navn'] . '%');
    }

    if (!empty($search['adresse'])) {
      $qb->andWhere('b.adresse LIKE :adresse')
        ->setParameter('adresse', '%' . $search['adresse'] . '%');
    }

    if (!empty($search['postBy'])) {
      $qb->andWhere('b.postBy LIKE :postBy')
        ->setParameter('postBy', '%' . $search['postBy'] . '%');
    }

    if (!empty($search['bygId'])) {
      $qb->andWhere('b.bygId = :bygId')
        ->setParameter('bygId', $search['bygId']);
    }

    if (!empty($search['postnummer'])) {
      $qb->andWhere('b.postnummer = :postnummer')
        ->setParameter('postnummer', $search['postnummer']);
    }

    if (!empty($search['status'])) {
      $qb->andWhere('b.status = :status')
        ->setParameter('status', $search['status']);
    }

    if (!empty($search['segment'])) {
      $qb->andWhere('b.segment = :segment')
        ->setParameter('segment', $search['segment']);
    }

    if (!$this->hasFullAccess($user)) {
      $qb->andWhere(':user MEMBER OF b.users');
      $qb->setParameter('user', $user);
    }

    return $qb->getQuery();
  }

  /**
   * Field sum
   *
   * @param User $user
   * @return array|\Doctrine\ORM\Query
   */
  public function getFieldSum(User $user, $field, $search) {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('sum(r.' . $field . ')')
      ->from('AppBundle:Bygning', 'b')
      ->leftJoin('b.rapport', 'r')
      ->leftJoin('b.segment', 's');

    if (!empty($search['segment'])) {
      $qb->andWhere('b.segment = :segment')
        ->setParameter('segment', $search['segment']);
    }

    if (!empty($search['forkortelse'])) {
      $qb->andWhere('s.forkortelse = :forkortelse')
        ->setParameter('forkortelse', $search['forkortelse']);
    }

    if (!empty($search['type'])) {
      $qb->andWhere('b.type = :type')
        ->setParameter('type', $search['type']);
    }

    if (!empty($search['year'])) {
      $qb->andWhere('YEAR(r.datering) = :year')
        ->setParameter('year', $search['year']);
    }

    if (!$this->hasFullAccess($user)) {
      $qb->andWhere(':user MEMBER OF b.users');
      $qb->setParameter('user', $user);
    }

    return $qb->getQuery();
  }


  /**
   * Field sum
   *
   * @param User $user
   * @return array|\Doctrine\ORM\Query
   */
  public function getFieldAvgDiff(User $user, $field, $baseline, $search) {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('(sum(r.' . $field . ') / sum(r.' . $baseline . ')) * (-100)')
      ->where('r.' . $field . ' IS NOT NULL')
      ->where('r.' . $baseline . ' IS NOT NULL')
      ->from('AppBundle:Bygning', 'b')
      ->leftJoin('b.rapport', 'r')
      ->leftJoin('b.segment', 's');

    if (!empty($search['segment'])) {
      $qb->andWhere('b.segment = :segment')
        ->setParameter('segment', $search['segment']);
    }

    if (!empty($search['forkortelse'])) {
      $qb->andWhere('s.forkortelse = :forkortelse')
        ->setParameter('forkortelse', $search['forkortelse']);
    }

    if (!empty($search['type'])) {
      $qb->andWhere('b.type = :type')
        ->setParameter('type', $search['type']);
    }

    if (!empty($search['year'])) {
      $qb->andWhere('YEAR(r.datering) = :year')
        ->setParameter('year', $search['year']);
    }

    if (!$this->hasFullAccess($user)) {
      $qb->andWhere(':user MEMBER OF b.users');
      $qb->setParameter('user', $user);
    }

    return $qb->getQuery();
  }

  /**
   * The ugly function to check if a user is allowed to do everything …
   *
   * @param $user
   * @return bool
   */
  private function hasFullAccess($user) {
    return $user && $user->hasRole('ROLE_ADMIN');
  }


  /**
   * Search for buildings with specific status and user
   *
   * @param \AppBundle\Entity\User $user
   * @param \AppBundle\DBAL\Types\BygningStatusType $status
   * @return \Doctrine\ORM\Query
   */
  public function getByUserAndStatus(User $user, BygningStatusType $status) {
    $qb = $this->_em->createQueryBuilder();

    $qb->select('b')
      ->from('AppBundle:Bygning', 'b');

    $qb->where('b.status = :status')->setParameter('status', $status);
    $qb->orderBy('b.updatedAt', 'DESC');

    if (!$this->hasFullAccess($user)) {
      $qb->andWhere(':user MEMBER OF b.users');
      $qb->setParameter('user', $user);
    }

    return $qb->getQuery();
  }

  /**
   * @param \AppBundle\Entity\User $user
   * @param \AppBundle\DBAL\Types\BygningStatusType $status
   * @return mixed
   * @throws \Doctrine\ORM\NoResultException
   * @throws \Doctrine\ORM\NonUniqueResultException
   */
  public function getSummaryByUserAndStatus(User $user, BygningStatusType $status) {
    $qb = $this->_em->createQueryBuilder();

    $qb->select('SUM(b.bruttoetageareal AS totalareal')
      ->from('AppBundle:Bygning', 'b');

    $qb->where('b.status = :status')->setParameter('status', $status);

    if (!$this->hasFullAccess($user)) {
      $qb->andWhere(':user MEMBER OF b.users');
      $qb->setParameter('user', $user);
    }

    return $qb->getQuery()->getSingleResult();
  }

  /**
   * Get all building types.
   * @return array
   */
  public function getBuildingTypes() {
    $qb = $this->_em->createQueryBuilder();

    $qb->select('b.type')
      ->distinct(TRUE)
      ->from('AppBundle:Bygning', 'b');

    return $qb->getQuery()->getResult();
  }
}
