<?php

namespace AppBundle\Entity;

/**
 * BygningStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BygningStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
