<?php
/**
 * @file
 * @TODO: Missing description.
 */

namespace AppBundle\Entity;

use AppBundle\DBAL\Types\ContactPersonReferenceType;
use Doctrine\ORM\EntityRepository;

/**
 * ContactPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactPersonRepository extends EntityRepository {
    public function findByEntity($entity) {
        $reference_type = strtolower((new \ReflectionClass($entity))->getShortName());
        if (!ContactPersonReferenceType::isValueExist($reference_type)) {
            return array();
        }
        return $this->findBy(array(
            'referenceType' => $reference_type,
            'referenceId' => $entity->getId(),
        ));
    }
}
