<?php
/**
 * @file
 * @TODO: Missing description.
 */

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\File\File;

/**
 * BilagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilRepository extends EntityRepository {
  public function saveContent($content, Fil $fil, ContainerInterface $container) {
    $dir = $container->getParameter('app.pdf_export.default_file_path');
    $filepath = $dir . '/' . uniqid();
    $fil->setFilepath($filepath);
    file_put_contents($fil->getFilepath(), $content);
    $file = new File($fil->getFilepath());
    $fil->setType($file->getMimeType());
  }

  public function findByEntity($entity) {
    $query = $this->_em->createQuery('SELECT f FROM AppBundle:Fil f WHERE f.entityType = :entity_type AND f.entityId = :entity_id ORDER BY f.createdAt');
    $query->setParameter('entity_type', get_class($entity));
    $query->setParameter('entity_id', $entity->getId());

    return $query->getResult();
  }
}
