<?php

namespace AppBundle\Entity;

/**
 * PumpeDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PumpeDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
