<?php
/**
 * @file
 * @TODO: Missing description.
 */

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use DateTime;

/**
 * PumpeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PumpeRepository extends EntityRepository {

  /**
   * Check if entity can be removed (deleted). If not, return an error message.
   *
   * @return string|null
   */
  public function getRemoveErrorMessage(Pumpe $pumpe) {
    $query = $this->_em->createQuery('SELECT d FROM AppBundle:PumpeTiltagDetail d WHERE d.pumpe = :pumpe');
    $query->setParameter('pumpe', $pumpe);
    $result = $query->getResult();

    if ($result) {
      return 'pumpe.error.in_use';
    }

    return null;
  }

  /**
   * Helper function to convert values to proper type.
   *
   * @param string $column
   * @param string $value
   *
   * @return string|DateTime
   *
   * @throws
   */
  public function getTypedValue($column, $value) {
    switch ($column) {
      case 'createdAt':
      case 'updatedAt':
        if (empty($value)) {
            $value = 'now';
        }
        return new \DateTime($value);
        break;

      default;
        // Most of values are stringable.
        return (string) $value;
    }
  }

}
