<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportRepository extends EntityRepository {

  /**
   * Get the Pumpetiltag for the rapport
   *
   * @param $rapport
   * @return \AppBundle\Entity\PumpeTiltag
   * @throws \Doctrine\ORM\NonUniqueResultException
   */
  public function getPumpeTiltag($rapport)
  {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('t')->from('AppBundle\Entity\Tiltag', 't')->where('t INSTANCE OF AppBundle\Entity\PumpeTiltag')->andWhere('t.rapport IN (:rapport)' )->setParameter( 'rapport', $rapport );

    $query = $qb->getQuery();

    return $query->getOneOrNullResult();
  }

}
