<?php

namespace AppBundle\Entity;

/**
 * RegningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegningRepository extends \Doctrine\ORM\EntityRepository
{
}
