<?php

namespace AppBundle\Entity;

/**
 * SegmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SegmentRepository extends \Doctrine\ORM\EntityRepository
{
}
