<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * VirksomhedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VirksomhedRepository extends EntityRepository
{
  public function getDatterSelskabReferenceList($currentVirksomhed)
  {
    $virksomheder = $this->findAll();
    $virksomhedTrail = new ArrayCollection();
    if ($currentVirksomhed instanceof Virksomhed) {
      $virksomhedTrail = $currentVirksomhed->getVirksomhedsTrail();
    }
    /** @var Virksomhed $virksomhed */
    foreach ($virksomheder as $key => $virksomhed) {
      if ($currentVirksomhed instanceof Virksomhed) {
        if ($virksomhedTrail->contains($virksomhed)) {
          unset($virksomheder[$key]);
        }

        if (!empty($virksomhed->getParent()) && $virksomhed->getParent()->getId() != $currentVirksomhed->getId()) {
          unset($virksomheder[$key]);
        }
      }
    }
    return $virksomheder;
  }

}
