<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VirksomhedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VirksomhedRepository extends EntityRepository
{
  public function getDatterSelskabReferenceList($currentVirksomhed)
  {
    $virksomheder = $this->findAll();
    /** @var Virksomhed $virksomheder */
    foreach ($virksomheder as $key => $virksomhed) {
      if ($currentVirksomhed instanceof Virksomhed) {
        if ($virksomhed->getId() == $currentVirksomhed->getId()) {
          unset($virksomheder[$key]);
        }
      }
    }
    return $virksomheder;
  }
  
}
