<?php

namespace AppBundle\Entity;

/**
 * VirksomhedKortlaegningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VirksomhedKortlaegningRepository extends \Doctrine\ORM\EntityRepository
{
}
